name = "bio1ixir-blog-theme"
license = "MIT"
licenselink = "https://github.com/bio1ixir/bio1ixir-blog-theme/LICENSE.md"
description = ""
homepage = "http://bio1ixir.github.io/"
tags = []
features = []
min_version = "0.38"

[author]
  name = "Archit Dwivedi"
  homepage = "https://e1ixir.netlify.com/"
